<div style='text-align: center; padding: 5px; width: 90%; wordwrap: break-word'><a href=/id/2569224><div style="background: #fff; color: #000; width: 100%;">AKCIEe .. EVENTZz</div></a>
{get_nodes_by_parent parent=2569224 listing_amount=3 offset=0} {foreach from=$get_nodes_by_parent item=node} {if $node.external_link neq "session://fook"} <div style='margin-bottom:13px'> <div class='header' style='text-align:center; height: 2em'> <a href='/id/{$node.node_id}'>{$node.node_name}</a> by <a href='/id/{$node.user_id}'>{$node.login}</a> |{$node.node_created|date_format:"%d.%m.%Y. - %H:%M:%S"} </div> <div style='text-align: left;'> {$node.node_content|strip_tags|truncate:180|stripslashes} </div> </div> {/if} {/foreach} </div>

<div style='text-align: center; padding: 5px; width: 90%; wordwrap: break-word'><a href=/id/2141033><div style="background: #fff; color: #000; width: 100%;">VIDEAa .. VIDEOZz</div></a>
{get_nodes_by_parent parent=2141033 listing_amount=3 offset=0} {foreach from=$get_nodes_by_parent item=node} {if $node.external_link neq "session://fook"} <div style='margin-bottom:13px'> <div class='header' style='text-align:center; height: 2em'> <a href='/id/{$node.node_id}'>{$node.node_name}</a> by <a href='/id/{$node.user_id}'>{$node.login}</a> |{$node.node_created|date_format:"%d.%m.%Y. - %H:%M:%S"} </div> <div style='text-align: left;'> {$node.node_content|strip_tags|truncate:180|stripslashes} </div> </div> {/if} {/foreach} </div>

<div style='text-align: center; padding: 5px; width: 90%; wordwrap: break-word'><a href=/id/1478948><div style="background: #fff; color: #000; width: 100%;">GALERIAa .. GALLERYy</div></a>
{get_nodes_by_parent parent=1478948 listing_amount=3 offset=0} {foreach from=$get_nodes_by_parent item=node} {if $node.external_link neq "session://fook"} <div style='margin-bottom:13px'> <div class='header' style='text-align:center; height: 2em'> <a href='/id/{$node.node_id}'>{$node.node_name}</a> by <a href='/id/{$node.user_id}'>{$node.login}</a> |{$node.node_created|date_format:"%d.%m.%Y. - %H:%M:%S"} </div> <div style='text-align: left;'> {$node.node_content|strip_tags|truncate:180|stripslashes} </div> </div> {/if} {/foreach} </div>

<div style='text-align: center; padding: 5px; width: 90%; wordwrap: break-word'><a href=/id/2591985><div style="background: #fff; color: #000; width: 100%;">ODKAZYy .. LINKZz</div></a>
{get_nodes_by_parent parent=2591985 listing_amount=3 offset=0} {foreach from=$get_nodes_by_parent item=node} {if $node.external_link neq "session://fook"} <div style='margin-bottom:13px'> <div class='header' style='text-align:center; height: 2em'> <a href='/id/{$node.node_id}'>{$node.node_name}</a> by <a href='/id/{$node.user_id}'>{$node.login}</a> |{$node.node_created|date_format:"%d.%m.%Y. - %H:%M:%S"} </div> <div style='text-align: left;'> {$node.node_content|strip_tags|truncate:180|stripslashes} </div> </div> {/if} {/foreach} </div>