<?php
$error_messages['K_EGOTRIP']="kcka si davas, brusko si mastis?";
$error_messages['K_GIVEN']="datanode uz si k udelil.uz to nehul";
$error_messages['K_SPENT']="nemas k. call dara rollins if you're stupid or john lilly if you're trendy";
$error_messages['NOT_IN_WALLET']="nemas na to. si chudobna sta kostolna mys";
$error_messages['NEW_PASSWORD_MISMATCH']="password don't match, try again";
$error_messages['INCORRECT_TEMPLATE_ID']="incorrect template_id";
$error_messages['INCORRECT_VECTOR']="incorrect vector";
$error_messages['WRITE_PERMISSION_ERROR']="nemas dostatocne prava na zapis do dotycnej nody";
$error_messages['READ_PERMISSION_ERROR']="nemas dostatocne prava na citanie obsahu tejto nody. PROSTE NEMAS DOSTATOCNE PRAVA NA CITANIE OBSAHU TEJTO NODY. JE TI TO JASNE?";
$error_messages['EVENT_PERMISSION_ERROR']="nemas dostatocne prava na vykonanie tohto skutku. jses proklet do sesteho kolena";
$error_messages['ADD_NO_CONTENT']='Noda bez obsahu sa pridat neda. Prosto neda. A basta.';
$error_messages['USER_NOT_FOUND']='user s dotycnym menom neexistuje. alebo existuje iba v tvojich predstavach';
$error_messages['EVENT_NOT_EXISTENT']='toto nieje svet v ktorom by sa dali vykonavat cinnosti ktore neexistuju';
$error_messages['EVENT_NOT_PERMITTED']='su veci na ktore prosto nemas pravo';
$error_messages['NOT_NUMERIC']='POST parameter is not numeric';
$error_messages['MAX_CHILDREN']='nieje mozne pridat dalsiu nodu kedze bol prekroceny pocet MAX_CHILDREN definovany v paragrafe 42 vyhlasky 23/2005, hlava 666';
$error_messages['UNDELETE_IMPOSSIBLE']='nemozes vratit do zivota to co nieje tvoje';
?>