<?php
define('DAILY_K',30);
define('REGISTRATION_VOTES',2); //too small so far

// logout after one hour
define('LOGOUT_IDLE_SEC', 3600);

// An attempt to remove hard-code constants from code
define('REGISTRATION_TEXT_NODE',791946);
define('REGISTRATION_REQUEST_NODE',2091448);
define('UNVERIFIED_REGISTRATIONS_NODE',1836516);

define('DEF_DATA_TEMPLATE',12);
define('DEF_GALLERY_TEMPLATE',1041658);
define('DEF_LAST_NODE',23);

define('DEF_MAX_LISTING_AMMOUNT',100);

// 1961061 citizens?
// 1061495 citizens?
// 1961070 citizens?

// 791946 ps.php
// 2228983 ps.php

// 2019721 nodes.php template
// 2091520 -||-

// F.inc, K.inc
// $senat_id = 876611;
// $K_id = 1961061;

// addEvent.inc
//    $params['node_parent'] = 2019771;

// addPlugin.inc
//    $params['node_parent'] = 2019772;

// addTemplate.inc
//    $params['node_parent'] = 2029360;

// configurePoll.inc
//$params['template_id']="1549834";

// delete.inc
// $new_parent_id=123456;

// login.inc
//    elseif ($set->getString('header_id') == 2091520) {

// masterize.inc 
// moved to trash

// remove_users.inc 
// a lot of different

// unfriend.inc
// $q = "update nodes set external_link='', node_parent=123456, node_vector='001234560$node_id' whe

// verify.inc
// node_vector='0000010120914480$userid' where node_id='$user

// vycisti_registracky.inc
// $q="delete from nodes where node_vector like '020914480$noda%'";

// resource.kyberia.php
// $params['node_parent'] = 2029360;

// node methodz detto, (add*)

// get_citizen_count.inc
// nodes.node_id=1961061

// get_k_filtred_nodes
// $node_id = 2472165;

// get_poll.php
// template_id='1549834

?>
