CREATE TABLE users (
  user_id int(13) NOT NULL default '0',
  login char(66) default NULL,
  password char(32) default NULL,
  icq char(10) default NULL,
  email char(50) default NULL,
  last_action timestamp(14) NOT NULL,
  user_action char(75) default NULL,
  user_status enum('waiting','restricted','newbie','user','protector','editor') default NULL,
  user_mode enum('normal','happy','sad','stoned','love','agressive') default NULL,
  user_ad enum('yes','no') default NULL,
  www char(50) default NULL,
  user_mail int(5) default NULL,
  user_mail_name char(40) default NULL,
  listing_amount int(8) default '32',
  charisma int(8) default NULL,
  happiness char(123) default NULL,
  sad char(123) default NULL,
  love char(123) default NULL,
  agressive char(123) default NULL,
  session_string char(64) default NULL,
  template_set char(23) default 'kyberia',
  old_user_id int(11) default NULL,
  PRIMARY KEY  (user_id),
  UNIQUE KEY session_string (session_string),
  UNIQUE KEY login (login)
) TYPE=MyISAM